#!/usr/bin/env python3
# Hey Emacs, this is -*-python-*-

from CobolSharp import *

import sys

def main():
    source = sys.argv[1]
    program = parse(open(source, 'rt'))
    print(program)

    for section in program.proc_div.sections_in_order():
        print()
        print(section.name)

        full_graph = section_stmt_graph(section)
        print_graph_stmts(full_graph)

        reachable = reachable_stmt_graph(full_graph)
        print_graph_stmts(reachable)

if __name__ == '__main__':
    main()
