#!/usr/bin/env python3
# Hey Emacs, this is -*-python-*-

# Copyright 2016 Peter Liljenberg <peter.liljenberg@gmail.com>
# Licensed under GPLv3, see file LICENSE in the top directory

from CobolSharp import command

if __name__ == '__main__':
    command.main()
